[package]
name = "redismodule_cmd"
version = "0.0.1"
authors = ["Zhao Lang <eltoshan@gmail.com>"]
edition = "2018"

[lib]
crate-type=["lib"]

[dependencies]
redis-module = "0.10.0"
dyn-clonable = "0.9.0"

[dev-dependencies]
redis-module = { version = "0.10.0", features = ["test"] }

